public enum TokenCode {
    CLASS, NUMBER, IDENTIFIER, ERR_LONG_ID, ERR_ILL_CHAR, LBRACE, RBRACE, INT, 
    COMMA, SEMICOLON, REAL, STATIC, VOID, LPAREN, RPAREN, ASSIGNOP, IF, ELSE, INCDECOP, RELOP, 
    MULOP, ADDOP, CONTINUE, RETURN, BREAK, FOR, EOF
}
